# Generated by Django 4.0.4 on 2022-04-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_providers_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='providers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.providers'),
        ),
    ]
